### ISSUE TITLE
Test Enable/Disable checkboxes don't work

### ISSUE THREAD

**Issue by dstults** [DranKof/NutCheck#5]
For whatever hair-brained reason, in VS2019, vanilla checkboxes can't be toggled???

EDIT: This was really stupid.

**Comment by DranKof** [comment]
Considering removing checkboxes entirely (silly VS) and converting to pull-down tabs because I'm going to have to implement ranges anyway. #7

**Comment by dstults** [comment]
There was a field called "Autocheck" that got somehow toggled, breaking them. It's fixed now.
